-- SEED DATA: Realistic initial jobs for Indonesia
INSERT INTO jobs (
  source_id, external_id, title, company, location, work_type, job_type, experience_level,
  salary_min, salary_max, salary_currency, description, requirements, benefits, tags, original_url, posted_at, content_hash
) VALUES
(
  (SELECT id FROM job_sources WHERE name = 'BCA Careers' LIMIT 1),
  'bca-it-support-01',
  'IT Support & Operations Specialist',
  'PT Bank Central Asia Tbk',
  'Jakarta Pusat',
  'onsite',
  'full_time',
  'entry',
  8500000,
  14000000,
  'IDR',
  'Bertanggung jawab atas pemeliharaan perangkat keras (hardware), sistem operasi, jaringan lokal cabang (LAN/WLAN), dan penanganan insiden teknologi informasi perbankan harian.',
  'Pendidikan S1 Teknik Informatika, Ilmu Komputer, atau Sistem Informasi dengan IPK minimal 3.00. Menguasai troubleshooting hardware, Windows Server, Active Directory, dan dasar jaringan TCP/IP.',
  'Tunjangan hari raya, bonus tantiem tahunan, asuransi kesehatan keluarga, program pelatihan sertifikasi IT perbankan.',
  ARRAY['IT Support', 'Hardware', 'Networking', 'Banking', 'Windows Server'],
  'https://karir.bca.co.id/it-support',
  NOW() - INTERVAL '2 days',
  md5('IT Support & Operations Specialist|PT Bank Central Asia Tbk|Jakarta Pusat')
),
(
  (SELECT id FROM job_sources WHERE name = 'Gojek Careers' LIMIT 1),
  'gojek-be-golang-02',
  'Senior Backend Engineer (Golang)',
  'Gojek',
  'Jakarta Selatan',
  'hybrid',
  'full_time',
  'senior',
  25000000,
  42000000,
  'IDR',
  'Merancang dan membangun arsitektur microservices skala masif jutaan transaksi harian pada ekosistem Gojek (Transport, Food, & Logistics).',
  'Pengalaman minimal 4 tahun dengan Golang atau Java. Memiliki pemahaman kuat tentang distributed systems, Kafka, Redis, PostgreSQL, dan Docker/Kubernetes.',
  'Asuransi kesehatan swasta internasional, alokasi tunjangan hybrid work, MacBook Pro M3, bonus kinerja tahunan.',
  ARRAY['Golang', 'Microservices', 'Kafka', 'PostgreSQL', 'Docker'],
  'https://www.gotocompany.com/careers/backend-engineer',
  NOW() - INTERVAL '1 day',
  md5('Senior Backend Engineer (Golang)|Gojek|Jakarta Selatan')
),
(
  (SELECT id FROM job_sources WHERE name = 'Tokopedia Careers' LIMIT 1),
  'tokopedia-fe-vue-03',
  'Frontend Engineer (Vue 3 / TypeScript)',
  'Tokopedia',
  'Jakarta Barat',
  'hybrid',
  'full_time',
  'mid',
  15000000,
  25000000,
  'IDR',
  'Mengembangkan fitur baru dan mengoptimalkan performa web marketplace Tokopedia dengan Vue.js 3, TypeScript, dan TailwindCSS.',
  'Pengalaman 2+ tahun dalam modern JavaScript/TypeScript framework (Vue/React). Memahami SSR, SEO optimization, state management Pinia, dan web performance tuning.',
  'Asuransi kesehatan rawat jalan & rawat inap, voucher diskon Tokopedia, tunjangan komunikasi, flexible working arrangement.',
  ARRAY['Frontend', 'Vue3', 'TypeScript', 'TailwindCSS', 'Vite'],
  'https://www.tokopedia.com/careers/fe-engineer',
  NOW() - INTERVAL '3 days',
  md5('Frontend Engineer (Vue 3 / TypeScript)|Tokopedia|Jakarta Barat')
),
(
  (SELECT id FROM job_sources WHERE name = 'Traveloka Careers' LIMIT 1),
  'traveloka-fullstack-04',
  'Full Stack Software Engineer',
  'Traveloka',
  'Tangerang Selatan',
  'hybrid',
  'full_time',
  'mid',
  18000000,
  30000000,
  'IDR',
  'Mengembangkan aplikasi pemesanan tiket penerbangan dan hotel end-to-end dengan arsitektur cloud terdistribusi di AWS.',
  'Keahlian dalam Java / Kotlin backend dan React / Vue frontend. Memahami REST API design, asynchronous processing, dan CI/CD pipeline.',
  'Tunjangan traveling tahunan, asuransi kesehatan komprehensif, makan siang gratis di kantor, program stock options.',
  ARRAY['Fullstack', 'Java', 'React', 'AWS', 'PostgreSQL'],
  'https://www.traveloka.com/en-id/careers/fullstack',
  NOW() - INTERVAL '4 days',
  md5('Full Stack Software Engineer|Traveloka|Tangerang Selatan')
),
(
  (SELECT id FROM job_sources WHERE name = 'Telkom Careers' LIMIT 1),
  'telkom-devops-05',
  'DevOps & Cloud Engineer',
  'PT Telkom Indonesia (Persero) Tbk',
  'Bandung',
  'hybrid',
  'full_time',
  'senior',
  16000000,
  27000000,
  'IDR',
  'Mengelola infrastruktur cloud BUMN, cluster Kubernetes, observabilitas sistem monitoring, serta mengotomatisasi delivery software berskala nasional.',
  'Pengalaman 3+ tahun mengelola Linux, Kubernetes, Terraform, Docker, GitLab CI, dan arsitektur hybrid cloud.',
  'Status pegawai BUMN tetap, tunjangan telekomunikasi, fasilitas kesehatan lengkap, dana pensiun BUMN.',
  ARRAY['DevOps', 'Kubernetes', 'Docker', 'Linux', 'Terraform'],
  'https://careers.telkom.co.id/devops',
  NOW() - INTERVAL '2 days',
  md5('DevOps & Cloud Engineer|PT Telkom Indonesia (Persero) Tbk|Bandung')
),
(
  (SELECT id FROM job_sources WHERE name = 'Bank Mandiri Careers' LIMIT 1),
  'mandiri-odp-06',
  'Officer Development Program (ODP) - IT',
  'PT Bank Mandiri (Persero) Tbk',
  'Jakarta Selatan',
  'onsite',
  'full_time',
  'entry',
  10000000,
  16000000,
  'IDR',
  'Program akselerasi kepemimpinan teknologi informasi untuk calon pimpinan IT perbankan terbesar di Indonesia.',
  'Lulusan baru (fresh graduate) S1/S2 Ilmu Komputer, Teknik Informatika, Sistem Informasi, Teknik Elektro dengan IPK minimal 3.00.',
  'Jalur karir manajerial cepat, asuransi kesehatan BUMN, bonus kinerja perbankan, fasilitas pembiayaan karyawan.',
  ARRAY['ODP', 'Banking', 'Management Trainee', 'Software Engineering'],
  'https://www.bankmandiri.co.id/karir/odp-it',
  NOW() - INTERVAL '5 days',
  md5('Officer Development Program (ODP) - IT|PT Bank Mandiri (Persero) Tbk|Jakarta Selatan')
),
(
  (SELECT id FROM job_sources WHERE name = 'Astra Careers' LIMIT 1),
  'astra-it-analyst-07',
  'IT Support & Infrastructure Analyst',
  'PT Astra International Tbk',
  'Jakarta Utara',
  'onsite',
  'full_time',
  'junior',
  9000000,
  15000000,
  'IDR',
  'Menangani troubleshooting perangkat IT, instalasi jaringan, implementasi sistem keamanan end-point, dan pemeliharaan server lokal.',
  'Pendidikan S1 di bidang terkait IT. Memiliki sertifikasi MCSA / CCNA menjadi nilai tambah. Kemampuan komunikasi yang baik.',
  'Koperasi karyawan Astra, fasilitas kesehatan keluarga, bonus tahunan Astra Group, program pelatihan berkelanjutan.',
  ARRAY['IT Support', 'Infrastructure', 'Cisco', 'Network', 'Hardware'],
  'https://www.astra.co.id/Career/it-analyst',
  NOW() - INTERVAL '6 days',
  md5('IT Support & Infrastructure Analyst|PT Astra International Tbk|Jakarta Utara')
),
(
  (SELECT id FROM job_sources WHERE name = 'Jobstreet' LIMIT 1),
  'jobstreet-mobile-flutter-08',
  'Mobile App Developer (Flutter / Dart)',
  'PT Shopee International Indonesia',
  'Jakarta Selatan',
  'hybrid',
  'full_time',
  'mid',
  14000000,
  24000000,
  'IDR',
  'Mengembangkan aplikasi mobile e-commerce dan financial services multi-platform berbasis Flutter dengan performa 60 FPS yang mulus.',
  'Pengalaman 2+ tahun dalam Flutter & Dart. Memahami State Management (Bloc / Riverpod), Clean Architecture, REST API, dan integrasi push notification.',
  'Tunjangan makan siang, asuransi kesehatan swasta, peralatan kerja Apple, voucher belanja.',
  ARRAY['Flutter', 'Dart', 'Mobile', 'Android', 'iOS'],
  'https://www.jobstreet.co.id/id/job-search/job-vacancy/flutter-developer',
  NOW() - INTERVAL '1 day',
  md5('Mobile App Developer (Flutter / Dart)|PT Shopee International Indonesia|Jakarta Selatan')
),
(
  (SELECT id FROM job_sources WHERE name = 'LinkedIn Jobs' LIMIT 1),
  'linkedin-qa-automation-09',
  'QA Automation Engineer',
  'PT Global Digital Niaga (Blibli)',
  'Jakarta Barat',
  'hybrid',
  'full_time',
  'mid',
  13000000,
  22000000,
  'IDR',
  'Menyusun skenario pengujian otomatis untuk web dan mobile application, melakukan stress test, dan mengintegrasikan testing ke dalam pipeline CI/CD.',
  'Pengalaman minimal 2 tahun dalam automated testing. Menguasai Playwright, Cypress, Selenium, JMeter, atau Appium. Memahami metodologi Agile/Scrum.',
  'Asuransi kesehatan lengkap, tunjangan kebugaran, program kepemilikan gadget, cuti tahunan tambahan.',
  ARRAY['QA', 'Automation', 'Playwright', 'Cypress', 'Testing'],
  'https://www.linkedin.com/jobs/view/qa-automation-blibli',
  NOW() - INTERVAL '2 days',
  md5('QA Automation Engineer|PT Global Digital Niaga (Blibli)|Jakarta Barat')
),
(
  (SELECT id FROM job_sources WHERE name = 'Glints' LIMIT 1),
  'glints-data-analyst-10',
  'Data Analyst & Business Intelligence',
  'Bukalapak',
  'Jakarta Selatan',
  'remote',
  'full_time',
  'mid',
  13000000,
  21000000,
  'IDR',
  'Mengolah data transaksi dan perilaku pengguna menjadi visualisasi dashboard interaktif serta memberikan rekomendasi bisnis berbasis data statistik.',
  'Mahir SQL tingkat lanjut, Tableau / PowerBI, Python/R dasar untuk data wrangling, serta pemahaman metrik e-commerce / fintech.',
  'Peluang kerja remote dari mana saja di Indonesia, tunjangan internet bulanan, asuransi rawat jalan swasta.',
  ARRAY['Data Analyst', 'SQL', 'Tableau', 'PowerBI', 'Python'],
  'https://glints.com/id/opportunities/jobs/data-analyst',
  NOW() - INTERVAL '3 days',
  md5('Data Analyst & Business Intelligence|Bukalapak|Jakarta Selatan')
),
(
  (SELECT id FROM job_sources WHERE name = 'Kalibrr' LIMIT 1),
  'kalibrr-uiux-11',
  'UI/UX Product Designer',
  'DANA Indonesia',
  'Jakarta Selatan',
  'hybrid',
  'full_time',
  'mid',
  14000000,
  23000000,
  'IDR',
  'Merancang antarmuka dan alur pengalaman pengguna aplikasi dompet digital nasional yang intuitif, accessible, dan menyenangkan.',
  'Portofolio desain yang solid dalam Figma. Memahami design system, user research, wireframing, prototyping, dan usability testing.',
  'Asuransi kesehatan komprehensif, tunjangan wellness, flexible working hours, budget training.',
  ARRAY['UI/UX', 'Figma', 'Product Design', 'Prototyping', 'Fintech'],
  'https://www.kalibrr.id/job-board/ui-ux-designer',
  NOW() - INTERVAL '4 days',
  md5('UI/UX Product Designer|DANA Indonesia|Jakarta Selatan')
),
(
  (SELECT id FROM job_sources WHERE name = 'Jobstreet' LIMIT 1),
  'jobstreet-it-support-12',
  'IT Helpdesk & Technical Support',
  'PT Solusi Teknologi Nusantara',
  'Bandung',
  'onsite',
  'full_time',
  'entry',
  6000000,
  9500000,
  'IDR',
  'Memberikan bantuan teknis bagi pengguna komputer kantor, instalasi software berlisensi, manajemen akun user, dan setup perangkat meeting video conference.',
  'Pendidikan minimal SMK / D3 / S1 Teknik Komputer / Informatika. Memahami dasar troubleshooting Windows dan Mac, printer sharing, dan kabel LAN.',
  'BPJS lengkap, tunjangan makan, lembur berbayar, lingkungan kerja kolaboratif.',
  ARRAY['IT Support', 'Helpdesk', 'Hardware', 'Windows', 'LAN'],
  'https://www.jobstreet.co.id/id/job-search/job-vacancy/it-helpdesk',
  NOW() - INTERVAL '1 day',
  md5('IT Helpdesk & Technical Support|PT Solusi Teknologi Nusantara|Bandung')
);
